name: publish.yml
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      registry_host:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      REGISTRY_TOKEN:
        required: true
      REGISTRY_USERNAME:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4
        with:
          repository: ElegantCone/aneki_frontend
          ref: master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry_host }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN  }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ inputs.registry_host }}/${{ inputs.image_name }}:${{ inputs.image_tag }}
            ${{ inputs.registry_host }}/${{ inputs.image_name }}:latest
